### ISSUE TITLE
Provide License to the project

### ISSUE THREAD

**Issue by kopp** [delftrobotics/dr_eigen#2]
It would be awesome if you could add a license to your project -- ideally a permissive one such as [MIT](https://choosealicense.com/licenses/mit/).
Currently, there is no `LICENSE.txt` (so github does not know about the license) but the `package.xml` states `all-rights-reserved`.
Currently [I am not allowed to use your code](https://choosealicense.com/no-permission/) that you provided on GitHub since "all rights (are) reserved" and I guess this is not the intention ;-)

If it is, this is also fine, please add a LICENSE.txt in that case, too, to stress this wish.

**Comment by hgaiser** [comment]
Should be fixed by https://github.com/fizyr/dr_eigen/pull/3

**Comment by kopp** [comment]
Yes, is fixed. Thanks!
