### ISSUE TITLE
add copyright notice

### ISSUE THREAD

**Issue by peter-urban** [delftrobotics/dr_eigen#4]
Hi,

I would like to use portions of this code (average quaterions) within a different open source project.
I can see that this repository is licensed under Appache 2, which requires me to add your copyright notice. However, I cannot find a copyright notice anywhere :-)

Could you add such a notice to the files, or state here which copyright notice to use?

Best regards
Peter

**Comment by de-vri-es** [comment]
Hey! Thanks for doing things correctly :)

You can add this notice:
```
Copyright 2014-2022, Fizyr B.V.
```

**Comment by de-vri-es** [comment]
I've also added a copyright statement to all source and header files :)

**Comment by peter-urban** [comment]
thx :-)
